### ISSUE TITLE
Same team member appearing multiple times

### ISSUE THREAD

**Issue by justWerns** [dev-launchers/site-projects#71]
As a user not currently associated with the Site Projects project, I see Mohammed listed twice under the Team section.
![image](https://user-images.githubusercontent.com/12598566/140421878-bd3308cc-2d7a-4544-a5b9-08a95562bc2f.png)
I did notice that the two Mohammed users have different email addresses.

**Comment by Enjoy2Live** [comment]
@justWerns I've looked at this and it seems like I was testing my other email with the backend and forgot it in the list, Now it shouldn't be there anymore :+1:
